// <auto-generated />
using System;
using FinalProjectShortenURL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProjectShortenURL.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20230307193602_FirstMigrationV1")]
    partial class FirstMigrationV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProjectShortenURL.Models.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublicIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URLModelShortURL")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("URLModelShortURL");

                    b.ToTable("Entry");
                });

            modelBuilder.Entity("FinalProjectShortenURL.Models.URLModel", b =>
                {
                    b.Property<string>("ShortURL")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CounterOfRequests")
                        .HasColumnType("int");

                    b.Property<string>("FullURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("URLCreated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UrlUserId")
                        .HasColumnType("int");

                    b.HasKey("ShortURL");

                    b.ToTable("Urls");
                });

            modelBuilder.Entity("FinalProjectShortenURL.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinalProjectShortenURL.Models.Entry", b =>
                {
                    b.HasOne("FinalProjectShortenURL.Models.URLModel", null)
                        .WithMany("Entries")
                        .HasForeignKey("URLModelShortURL");
                });

            modelBuilder.Entity("FinalProjectShortenURL.Models.URLModel", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
